import Head from 'next/head'
import { motion, AnimatePresence } from 'framer-motion'
import Modal from '../components/Modal'
import { useState } from 'react'

export default function Home() {

  const [modalOpen, setModalOpen] = useState(false)

  const close = () => setModalOpen(false)
  const open = () => setModalOpen(true)

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <motion.button
          whileHover={{scale: 1.1}}
          whileTap={{scale: .9}}
          className='save-button'
          onClick={() => (modalOpen ? close() : open())}
        >
          Lauch modal
        </motion.button>

        <AnimatePresence
          initial={false}
          exitBeforeEnter={true}
        >
          {modalOpen && <Modal handleClose={close} />}
        </AnimatePresence>

      </main>
    </div>
  )
}
